import Head from "next/head";
import Row1 from "../src/components/Row1";
import Hulu from "../src/components/Hulu";
import Prime from "../src/components/Prime";
import Netflix from "../src/components/Netflix";
import Row8 from "../src/components/Row8";
import Row9 from "../src/components/Row9";
import styles from "../styles/Home.module.css";

export default function Home({ hulu, prime }) {
  console.log(hulu);
  console.log(prime);

  return (
    <div className={styles.container}>
      <Head>
        <title>Periodic Table of Telements</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Periodic Table of Telements</h1>
      <small>With Next JS and CSS Grid</small>
    
      <Row1 />
      <Hulu hulu={hulu} />
      <Prime prime={prime} />
      <Netflix />
      <Row8 />
      <Row9 />
    </div>
  );
}

export async function getStaticProps() {
  // ******* hulu start
  const res = await fetch(
    "https://streaming-availability.p.rapidapi.com/search/basic?country=us&service=prime&type=series&genre=18&page=20&output_language=en&language=en",
    {
      method: "GET",
      headers: {
        "x-rapidapi-host": "streaming-availability.p.rapidapi.com",
        "x-rapidapi-key": process.env.PRIVATE_API_KEY,
      },
    }
  );

  const hulu = await res.json();

  // ******* hulu end

  // ******* prime start
  const primeRes = await fetch(
    "https://streaming-availability.p.rapidapi.com/search/basic?country=us&service=prime&type=movie&genre=18&page=20&output_language=en&language=en",
    {
      method: "GET",
      headers: {
        "x-rapidapi-host": "streaming-availability.p.rapidapi.com",
        "x-rapidapi-key": process.env.PRIVATE_API_KEY,
      },
    }
  );

  const prime = await primeRes.json();

  // ******* prime end

  return {
    props: {
      hulu,
      prime,
    },
  };
}
