import Head from "next/head";
import Row1 from "../src/components/Row1";
import Hulu from "../src/components/Hulu";
import Row3 from "../src/components/Row3";
import Row4567 from "../src/components/Row4567";
import Row8 from "../src/components/Row8";
import Row9 from "../src/components/Row9";
import styles from "../styles/Home.module.css";

export default function Home({ hulu }) {
  console.log(hulu);

  return (
    <div className={styles.container}>
      <Head>
        <title>Periodic Table of Telements</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Periodic Table of Telements</h1>
      <small>With Next JS and CSS Grid</small>
      <ul>
        {hulu.results.slice(0, 2).map((h) => (
          <li key={h.title}>{h.title}</li>
        ))}
      </ul>

      {hulu.results.slice(3, 8).map((h) => (
        <h1>{h.title}</h1>
      ))}

      <Row1 />
      <Hulu hulu={hulu} />
      <Row3 />
      <Row4567 />
      <Row8 />
      <Row9 />
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    "https://streaming-availability.p.rapidapi.com/search/basic?country=us&service=hulu&type=movie&genre=18&page=1&output_language=en&language=en",
    {
      method: "GET",
      headers: {
        "x-rapidapi-host": "streaming-availability.p.rapidapi.com",
        "x-rapidapi-key": "49c3b5daa1mshc9c11e33472e817p104d34jsn3f54bf21e0d7",
      },
    }
  );
  const hulu = await res.json();

  return {
    props: { hulu },
  };
}
